# Site settings
author: ted sazon
title: belated
header-img: img/home-bg.png
email: tedsazon@gmail.com
copyright_name: ted sazon
description: > # this means to ignore newlines until "baseurl:"
  an unexpecTed journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tedsazon

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
